### ISSUE TITLE
5.x-codecomplete-netcore branch does not build

### ISSUE THREAD

**Issue by kroffdaddy** [elastic/elasticsearch-net-example#19]
After cloning the *elasticsearch-net-example* repo, having selected the *5.x-codecomplete-netcore* branch, I tried `dotnet restore` from the *NuSearch.Web* folder, which results in the following error:

```
Package Elasticsearch.Net 5.5.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Elasticsearch.Net 5.5.0 supports:\r
```

**Comment by russcam** [comment]
Hey @kroffdaddy, you've jumped on this branch a little too early 😄 

There are some changes that need to be merged into it from another branch first but it should still be compilable right now if you want an early look. Sadly, there are several bugs in the .NET Core runtime in SDK 1.0.4 which means 

1. that it only looks in the global NuGet cache for packages, rather than the local packages directory. [You can fix this by following the troubleshooting guide.](https://github.com/elastic/elasticsearch-net-example/tree/5.x-codecomplete-netcore#troubleshooting)
2. `dotnet restore` can fail even though the packages it is restoring _are_ compatible, like Elasticsearch.Net, which is `netstandard13` compatible. You can fix this by deleting both the `obj` and `bin` directories in `NuGet.Web`, as well as all packages in `packages` folder.

I'm going to close this for now as these details will be in the final guide when it's truly ready!
